---
title: "Lab3"
output: html_document
date: "2022-11-26"
---

# Lab3

```{r}
TIN <- 20

# set.seed(TIN) TODO: uncomment
```

## Part I: Markov Chain

### Problem 1

```{r}
TLN <- paste("0", TIN, sep = "")
```

Transition probabilities matrix:

$$
P=\begin{bmatrix}
0.9 & 0.1 & 0 & 0\\
0.8 & 0.1 & 0.1 & 0\\
0.9 & 0 & 0 & 0.1\\
0.8 & 0.1 & 0.1 & 0\\
\end{bmatrix}
$$

```{r}
P = matrix(c(
  0.9, 0.1, 0.0, 0.0,
  0.8, 0.1, 0.1, 0.0,
  0.9, 0.0, 0.0, 0.1,
  0.8, 0.1, 0.1, 0), nrow=4, byrow=T)

calculate_by_eigenvector <- function (probs) {
  left_eigenvector <- eigen(t(probs))$vectors[,1]
  return (sapply(left_eigenvector / sum(left_eigenvector), Re))
}

calculate_by_matrix_multiplication <- function (probs) {
  return ((probs %*% probs %*% probs %*% probs)[1, ])
}

cat("Transition probabilities (eigenvectors): ", calculate_by_eigenvector(P), "\n")
cat("Transition probabilities (matrices): ", calculate_by_matrix_multiplication(P))

```

```{r}
estimate_probability <- Vectorize(function (m, n) {
  sample_data <- apply(
    replicate(m, sample(0:9, n, replace = T)), 2,
    function(x) grepl(TLN, paste(x, collapse = "")))
  return (length(sample_data[sample_data == TRUE]) / length(sample_data))
})

theoretical_probability <- function (n) 1 - ((1 - 0.001) ^ n)
# 0.001 is the limiting probability of the state 4
```

```{r}
x <- seq(100, 2000, by = 100)
estimated_data = estimate_probability(500, x)
theoretical_data = theoretical_probability(x)
```

```{r}
plot(
  x,
  estimated_data, col ="blue", lwd = 3)
lines(
  x,
  theoretical_data)
```

$$
P(|\bar{X}-\mu|\leq\varepsilon)=1-2\Phi(-\frac{\sqrt{n}}{\sigma}\varepsilon) \\
1-2\Phi(-\frac{\sqrt{n}}{\sigma}\varepsilon)=0.95 \\
\Phi(-\frac{\sqrt{n}}{\sigma}\varepsilon)=0.025 \\
\sqrt{n}=-\frac{\sigma\cdot z_{0.025}}{\varepsilon} \\
n=\sigma^2(\frac{z_{0.025}}{\varepsilon})^2 \\
n=p_n\cdot(1-p_n)\cdot(\frac{z_{0.025}}{0.03})^2 \\
n=(1-0.999^{1000})\cdot(0.999^{1000})\cdot(\frac{z_{0.025}}{0.03})^2 \\
n\sim992 
$$

```{r}
x <- seq(500, 1000, by = 100)
n <- 1000
m <- 100
estimated_data = apply(replicate(m, estimate_probability(x, n) - theoretical_probability(n)), 1, function (x) quantile(x, .95))
plot(
  x,
  estimated_data, col ="blue", lwd = 3, type="l")
abline(h = 0.03, col = "darkgreen")
```

```{r}
N <- 1000
n <- 1000
m <- 100
hist(
  replicate(m, abs(estimate_probability(N, n) - theoretical_probability(n))),
  main = "Absolute error histogram",
  xlab = "Absolute error")
```

### Problem 2

Transition probabilities matrix:

$$
P=\begin{bmatrix}
0.9 & 0.1 & 0 & 0\\
0.8 & 0.1 & 0.1 & 0\\
0.9 & 0 & 0 & 0.1\\
0 & 0 & 0 & 1\\
\end{bmatrix}
$$

$$
\begin{cases}
\mu_1=1+0.9\cdot\mu_1+0.1\cdot\mu_2 \\
\mu_2=1+0.8\cdot\mu_1+0.1\cdot\mu_2+0.1\cdot\mu_3 \\
\mu_3=1+0.9\cdot\mu_1+0.1\cdot\mu_4 \\
\mu_4=0
\end{cases}
\Rightarrow
\begin{cases}
\mu_1=\frac{1+0.1\cdot\frac{1+0.8\cdot\mu_1+0.1\cdot(1+0.9\cdot\mu_1)}{0.9}}{0.1} \\
\mu_2=\frac{1+0.8\cdot\mu_1+0.1\cdot(1+0.9\cdot\mu_1)}{0.9} \\
\mu_3=1+0.9\cdot\mu_1 \\
\mu_4=0
\end{cases}
\\
\begin{cases}
\mu_1=10+\frac{10}{9}+\frac{8}{9}\mu_1+\frac{1}{9}+\frac{1}{10}\mu_1\Rightarrow\frac{90-80-9}{90}\mu_1=\frac{101}{9}\Rightarrow\mu_1=1010 \\
\mu_2=\frac{1+0.8\cdot\mu_1+0.1\cdot(1+0.9\cdot\mu_1)}{0.9}=\frac{10}{9}+\frac{8}{9}\mu_1+\frac{1}{9}+\frac{1}{10}\mu_1=\frac{11}{9}+\frac{89}{90}\mu_1=1000 \\
\mu_3=1+0.9\cdot\mu_1=1+909=910 \\
\mu_4=0
\end{cases}
$$

Hence, the estimated length is $\mu_1=1010$

```{r}
calculate_length <- Vectorize(function() {
  values <- vector()
  length <- 0
  while (paste(values, collapse = "") != TLN) {
    values <- tail(append(values, sample(0:9, 1)), nchar(TLN))
    length <- length + 1
  }
  return (length)
})

data <- replicate(100, calculate_length())
mean(data)
```

$$
P(|\hat{\theta}-\theta|<k\sigma)=1-
P(|\hat{\theta}-\theta|\geq k\sigma)\geq1-\frac{\sigma^2}{\sigma^2k^2}=1-\frac{1}{k^2} \\
1-\frac{1}{k^2}=0.95\Rightarrow k^2=20 \\
\sigma=\frac{\sigma_S}{\sqrt{n}} \\
k\sigma=10\Rightarrow\frac{\sigma_S}{\sqrt{n}}=\frac{10}{k}\Rightarrow n=\frac{\sigma_S^2\cdot k^2}{100}=\frac{\sigma_S^2}{5}
$$

```{r}
var(data) / 5
```

## Part II: Parameter estimation

### Problem 3

```{r}
theta <- TIN / 10
m <- 500
x <- seq(100, 500, by=100)

estimate_method_1 <- function(data, alpha) {
  n <- length(data)
  mu = sum(data) / n
  start = (2 * n * mu) / (qchisq(df = 2 * n, p = 1 - alpha / 2))
  end = (2 * n * mu) / (qchisq(df = 2 * n, p = alpha / 2))
  bounds <- c(start, end)
  return (bounds)
}

estimate_method_2 <- function(data, alpha) {
  n <- length(data)
  mu = sum(data)/n
  start = mu - (theta * qnorm(1 - alpha/2))/sqrt(n)
  end = mu + (theta * qnorm(1 - alpha/2))/sqrt(n)
  return (c(start, end))
}

estimate_method_3 <- function(data, alpha) {
  
}

estimate_method_4 <- function(data, alpha){
}

calculate_percentage <- function(n, alpha, method) {
  func <- function (data) method(data, alpha)
  sample_data <- apply(matrix(rexp(n * m, 1 / theta), nrow = m), 1, func)
  cmp <- Vectorize(function (x) x[1])
  return (length(sample_data[,sample_data[1,] < theta & theta < sample_data[2,]]) / length(sample_data))
}

plot_method <- function(n, alpha, method) {
  func <- Vectorize(function (n) calculate_percentage(n, alpha, method))
  plot(
    x,
    func(x),
    type = "l"
  )
}

plot_all <- function (method) {
  plot_method(x, .1, method)
  plot_method(x, .05, method)
  plot_method(x, .01, method)
}
```

```{r}
plot_all(estimate_method_1)
```

```{r}
plot_all(estimate_method_2)
```
